### ISSUE TITLE
Touchscreen Pi won't boot

### ISSUE THREAD

**Issue by rjmunro** [staldates/av-control#1]
After friday's lightning strike, the touchscreen Pi wouldn't boot - presumably the SD card was corrupted, or it suffered some other hardware problem.

There was no spare pi or spare SD card with the software on it, so we had to use the Lighting netbook as a backup controller. Unfortunately, this has a very outdated version of the software on it, so we could not control the power switchers and had to override them manually.

Can we get a couple of spare SD cards and make it routine to upgrade them when we upgrade the system? Also a couple of spare Pis in the cupboard in case they suffer hardware issues and we need to swap them out.

Also consider reinstating the backup manual switches on the power, but perhaps hide them a bit, next to the master Pi, for example.

**Comment by rjmunro** [comment]
@jamesremuscat I'm guessing we can close this now? Or is it still here to remind us to make backup SD cards?

**Comment by jamesremuscat** [comment]
This can probably be closed after all this time ;-)
