### ISSUE TITLE
Upgrade cameras and screens to HD

### ISSUE THREAD

**Issue by rjmunro** [staldates/av-control#18]
I know there are plans afoot. It would be good to track progress of this here or elsewhere.

**Comment by jamesremuscat** [comment]
There are plans afoot for tracking progress too ;-)

**Comment by rjmunro** [comment]
Reading this back, I realise what I meant might not have been clear. By progress, I meant progress in the plan, not progress in the actual installation.

It would be good to have something we can comment on and submit PRs to. E.g. I'd like to request that we look into a way to hang the cameras 30-40cm below the bars, rather than have them on top.

Currently, the shots look a bit rubbish angled down the whole time. Especially when we are in the round as the stage is both lower and closer.

If we could figure out a way to make them adjustable so they can go even lower for in the round, that would be ideal (adjustable by climbing a ladder and changing how they are mounted is fine -
adjustable by pressing a button would be great - systems exist, but would probably be outside our budget).

**Comment by jamesremuscat** [comment]
Oh, I see... :-)

Feel free to add such comments here for now - at some point I'll be making the draft design document available to the team for comment via Google Drive. It's (necessarily) at a quite advanced stage but still open to modification in the detail, and will be a "working document" until the installation has been completed in August.

To your point: the cameras specced are capable of being installed upside-down, so we can straight away gain ~6 inches by doing so on the current mounting plates. I imagine one could find or construct some sort of extension pole if one desired.

**Comment by jamesremuscat** [comment]
Barring a couple of small IRL tasks, the upgrade is complete; hence closing this. Anything specific, please raise a new issue.
